### ISSUE TITLE
could you provide the whole scripts for data preparation? 

### ISSUE THREAD

**Issue by wangpichao** [ictnlp/DASpeech#1]
I notice that the data preparation is kind of complex. Could you kindly provide the scripts for data preparation? Thank you.

**Comment by Poeroz** [comment]
Thank you for your interest in our work. Yes, the script for data preparation is quite complex. We are currently reorganizing and simplifying the previous data processing script, and we will release it as open source as soon as possible.

In general, the data processing scripts for S2TT and TTS are modifications based on the following two scripts. For S2ST, the data involves concatenating the data from S2TT and TTS. You can refer to the following two scripts now:

1. https://github.com/facebookresearch/fairseq/blob/main/examples/speech_to_text/prep_covost_data.py
2. https://github.com/facebookresearch/fairseq/blob/main/examples/speech_synthesis/preprocessing/get_feature_manifest.py

**Comment by Poeroz** [comment]
Hello, we have preliminarily released the data preprocessing scripts. You can refer to [this documentation](https://github.com/ictnlp/DASpeech/blob/main/DATA_PREPARE.md).

**Comment by wangpichao** [comment]
Thanks and will read it.
