### ISSUE TITLE
Data preparation步骤

### ISSUE THREAD

**Issue by guitarj** [ictnlp/DASpeech#2]
您好，想请教一下Data preparation的第二步和第四步，有提供相对应的code吗，还是要自己另外写?谢谢!

**Comment by Poeroz** [comment]
Hello, we have preliminarily released the data preprocessing scripts. You can refer to [this documentation](https://github.com/ictnlp/DASpeech/blob/main/DATA_PREPARE.md).

**Comment by guitarj** [comment]
OK,thanks!
