### ISSUE TITLE
ModuleNotFoundError: No module named 'examples.speech_synthesis'

### ISSUE THREAD

**Issue by guitarj** [ictnlp/DASpeech#3]
Traceback (most recent call last):
  File "/home/csmxj/DASpeech/translatotron/preprocess/prep_cvss_c_multilingual_data.py", line 25, in <module>
    from examples.speech_synthesis.data_utils import extract_logmel_spectrogram
ModuleNotFoundError: No module named 'examples.speech_synthesis'

1.这里好像是一个error?要呼叫fairseq/speech_synthesis/data_utils.py中的class extract_logmel_spectrogram时抓不到路径。
2.另外--covost-data-root data/covost2/一定要准备吗，无法只使用cvss-c?

**Comment by Poeroz** [comment]
Hello,

1. You can try running `python setup.py build develop` in the `fairseq/` directory.
2. Yes. You need to download covost2 dataset because the cvss-c dataset only contains the target speech and text. The source audio should be derived from covost2.
