### ISSUE TITLE
Infer the S2T pre-trained model!

### ISSUE THREAD

**Issue by swoboo** [ictnlp/DASpeech#5]
How do I infer the S2T pre-trained model?

**Comment by swoboo** [comment]
I tried fairseq-generate, but it seems like the inference results aren't accurate! During pre-training, the dev BLEU score could reach above 70, but when I performed inference on the test and dev.tsv separately, the performance was very poor. Do I need to rewrite the S2T inference code myself?

**Comment by Poeroz** [comment]
Hi, Thanks for your interest in our work! You can try the following script for S2T inference.

```
exp=$1
checkpoint_dir=checkpoints/$exp

python fairseq/scripts/average_checkpoints.py \
    --inputs $checkpoint_dir/checkpoint.best_bleu*.pt \
    --output $checkpoint_dir/average_best_checkpoint.pt

fairseq-generate data/cvss-c/fr-en/fbank2phone \
    --user-dir DASpeech \
    --config-yaml config.yaml --gen-subset test --task nat_speech_to_text \
    --path $checkpoint_dir/average_best_checkpoint.pt \
    --iter-decode-max-iter 0 --iter-decode-eos-penalty 0 --beam 1 \
    --max-tokens 20000 --scoring sacrebleu \
    --model-overrides "{\"decode_strategy\":\"lookahead\",\"decode_beta\":1}"
```

**Comment by swoboo** [comment]
Thanks a lot,it worked.
